In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 

In [2]:
df=pd.read_excel('E:\PYTHON\projects\Data set\Ghutukade.xlsx')

In [4]:
df.head()

Skewness   Kurtoisis     Mean   Variance       STD     Range fault
0  12.361618  220.873221  0.008814  0.000697  0.026399  0.829793    Cl
1  13.238493  232.448511  0.011655  0.001418  0.037663  1.046110    Cl
2  14.157957  258.835709  0.010427  0.001018  0.031901  0.805151    Cl
3  13.087721  316.638718  0.008220  0.000911  0.030176  0.850000    Cl
4  13.693464  276.508578  0.010124  0.000923  0.030382  0.843819    Cl

In [6]:
X=df.iloc[:,:-1]

In [8]:
y=df.fault

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
scaler=StandardScaler()

In [13]:
X=pd.DataFrame(scaler.fit_transform(X),columns=X.columns)

In [15]:
df.fault.unique()

array(['Cl', 'IRD', 'Mis', 'ORD', 'Un'], dtype=object)

In [16]:
y=df.fault.map({'Cl':1, 'IRD':2, 'Mis':3, 'ORD':4, 'Un':5})

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [20]:
from sklearn.tree import DecisionTreeClassifier

In [21]:
dt=DecisionTreeClassifier()

In [22]:
dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [23]:
dt.score(X_train,y_train)

1.0

In [24]:
dt.score(X_test,y_test)

0.75

In [27]:
y_pred=dt.predict(X_test)

In [28]:
y_pred

array([1, 2, 3, 5, 2, 3, 4, 2, 1, 3, 4, 4], dtype=int64)

In [29]:
y_test

11    1
21    2
33    3
58    5
36    4
31    3
42    4
13    2
30    3
2     1
41    4
37    4
Name: fault, dtype: int64

In [30]:
from sklearn.metrics import classification_report

In [32]:
cr=classification_report(y_pred,y_test)

In [34]:
print(cr)

              precision    recall  f1-score   support

           1       0.50      0.50      0.50         2
           2       1.00      0.67      0.80         3
           3       0.67      0.67      0.67         3
           4       0.75      1.00      0.86         3
           5       1.00      1.00      1.00         1

    accuracy                           0.75        12
   macro avg       0.78      0.77      0.76        12
weighted avg       0.77      0.75      0.75        12



In [35]:
from sklearn.metrics import confusion_matrix

In [37]:
cm=confusion_matrix(y_pred,y_test)

In [38]:
cm

array([[1, 0, 1, 0, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 1]], dtype=int64)

In [39]:
from sklearn.model_selection import cross_val_score

In [41]:
cv=cross_val_score(dt,X_train,y_train)

In [42]:
cv

array([0.9       , 0.9       , 0.6       , 0.88888889, 0.88888889])

In [43]:
cv.mean()

0.8355555555555554

In [45]:
from sklearn.model_selection import GridSearchCV
parameters= {
    'max_depth': [2, 3, 5, 10, 20],
    'min_samples_leaf': [5, 10, 20, 50, 100],
    'criterion': ["gini", "entropy"]
}

In [46]:
model=GridSearchCV(dt,parameters)

In [48]:
model.fit(X_train,y_train)

GridSearchCV(estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [2, 3, 5, 10, 20],
                         'min_samples_leaf': [5, 10, 20, 50, 100]})

In [49]:
model.best_params_

{'criterion': 'gini', 'max_depth': 10, 'min_samples_leaf': 5}

In [50]:
model.best_score_

0.8555555555555555