In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df=pd.read_excel('E:\PYTHON\projects\Data set\Ghutukade.xlsx')
df.head()

Skewness   Kurtoisis     Mean   Variance       STD     Range fault
0  12.361618  220.873221  0.008814  0.000697  0.026399  0.829793    Cl
1  13.238493  232.448511  0.011655  0.001418  0.037663  1.046110    Cl
2  14.157957  258.835709  0.010427  0.001018  0.031901  0.805151    Cl
3  13.087721  316.638718  0.008220  0.000911  0.030176  0.850000    Cl
4  13.693464  276.508578  0.010124  0.000923  0.030382  0.843819    Cl

In [3]:
X=df.iloc[:,:-1]

In [4]:
y=df.fault

In [5]:
scaler=StandardScaler()

In [6]:
scaler.fit_transform(X)
X=pd.DataFrame(scaler.fit_transform(X),columns=X.columns)

In [7]:
df.fault.unique()

array(['Cl', 'IRD', 'Mis', 'ORD', 'Un'], dtype=object)

In [8]:
y=df.fault.map({'Cl':1,'IRD':2,'Mis':3,'ORD':4,'Un':5})

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [10]:
from sklearn.linear_model import LogisticRegression

In [11]:
log=LogisticRegression(random_state=0,multi_class='auto')

In [12]:
log.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [13]:
y_pred=log.predict(X_test)
y_pred

array([2, 2, 5, 2, 3, 2, 5, 1, 3, 4, 1, 5], dtype=int64)

In [14]:
log.score(X_test,y_test)

0.6666666666666666

In [15]:
log.score(X_train,y_train)

0.875

In [16]:
from sklearn.model_selection import cross_val_score

In [17]:
cv=cross_val_score(log,X_train,y_train)

In [18]:
cv

array([0.8       , 0.7       , 0.7       , 0.88888889, 0.88888889])

In [19]:
cv.mean()

0.7955555555555556

In [20]:
from sklearn.metrics import classification_report

In [21]:
cr=classification_report(y_pred,y_test)

In [22]:
print(cr)

              precision    recall  f1-score   support

           1       1.00      0.50      0.67         2
           2       1.00      0.50      0.67         4
           3       1.00      0.50      0.67         2
           4       0.20      1.00      0.33         1
           5       1.00      1.00      1.00         3

    accuracy                           0.67        12
   macro avg       0.84      0.70      0.67        12
weighted avg       0.93      0.67      0.72        12



In [23]:
from sklearn.metrics import confusion_matrix

In [24]:
cm=confusion_matrix

In [25]:
cm(y_pred,y_test)

array([[1, 0, 0, 1, 0],
       [0, 2, 0, 2, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 3]], dtype=int64)

In [26]:
from sklearn.model_selection import GridSearchCV
parameters={"C":np.logspace(-3,3,7), "penalty":["l1","l2"]}

In [27]:
model=GridSearchCV(log,parameters)

In [28]:
model.fit(X_train,y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 598, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1306, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 443, in _check_solver
    raise ValueError("Solver %s supports only 'l2' or 'none' penalties, "
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  warnings.warn("Estimator fit failed. The score on this train-test"
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_v

GridSearchCV(estimator=LogisticRegression(random_state=0),
             param_grid={'C': array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03]),
                         'penalty': ['l1', 'l2']})

In [29]:
model.best_params_

{'C': 100.0, 'penalty': 'l2'}

In [30]:
model.best_score_

0.8755555555555556

In [31]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)
# define model
model = LogisticRegression(multi_class='ovr')
# fit model
model.fit(X, y)
# make predictions
yhat = model.predict(X)

In [32]:
yhat

array([1, 0, 1, 2, 0, 2, 1, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 1, 0, 0, 1,
       0, 2, 0, 0, 2, 0, 1, 1, 2, 1, 0, 2, 0, 0, 0, 1, 1, 2, 2, 1, 0, 1,
       0, 2, 0, 0, 0, 2, 0, 1, 2, 0, 2, 2, 1, 2, 1, 0, 2, 2, 2, 1, 0, 1,
       1, 1, 0, 2, 0, 2, 2, 1, 0, 0, 0, 0, 0, 1, 2, 0, 2, 0, 2, 2, 2, 1,
       0, 1, 2, 1, 1, 1, 0, 2, 0, 2, 1, 1, 0, 1, 1, 0, 0, 0, 2, 2, 2, 2,
       1, 0, 0, 1, 2, 0, 0, 0, 0, 2, 2, 2, 1, 0, 1, 2, 2, 0, 1, 0, 2, 1,
       0, 0, 2, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 2, 0, 0, 1, 1, 1, 2, 1,
       0, 0, 2, 2, 1, 0, 2, 1, 2, 2, 1, 0, 2, 0, 2, 1, 0, 0, 0, 0, 0, 1,
       2, 0, 2, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 2, 1, 0, 0, 1, 1, 0,
       2, 1, 1, 0, 1, 1, 0, 0, 0, 1, 2, 2, 0, 2, 0, 1, 0, 2, 2, 0, 0, 2,
       2, 1, 2, 2, 1, 0, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 0, 2, 2,
       2, 2, 0, 0, 0, 1, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 0, 1, 1, 0, 1, 2,
       1, 2, 0, 2, 0, 0, 0, 2, 1, 1, 0, 0, 1, 1, 2, 0, 1, 1, 1, 1, 2, 0,
       0, 0, 1, 2, 0, 0, 1, 0, 0, 2, 0, 0, 2, 1, 2,